#!/bin/sh
if ! command -v openssl >/dev/null 2>&1 ; then
  echo "Error: Could not find openssl in \$PATH: $PATH"
  exit 1
fi

if test -f necrospider.key; then
  echo "Error: necrospider.key already exists"
  exit 1
fi

if test -f necrospider.crt; then
  echo "Error: necrospider.crt already exists"
  exit 1
fi

openssl req -new -newkey rsa:4096 -sha256 -x509 -days 365 -nodes -out necrospider.crt -keyout necrospider.key -subj "/CN=localhost"

chmod 600 necrospider.crt
chmod 600 necrospider.key
